// Code generated by go generate; DO NOT EDIT.
package avdimagetypes

const (
	V2LayerNameDefinition                 = "V2LayerName"
	V2BuildParameterNameDefinition        = "V2BuildParameterName"
	V2BuildParameterValueDefinition       = "V2BuildParameterValue"
	V2CustomizerWindowsUpdateDefinition   = "V2CustomizerWindowsUpdate"
	V2CustomizerWindowsRestartDefinition  = "V2CustomizerWindowsRestart"
	V2CustomizerFileDefinition            = "V2CustomizerFile"
	V2CustomizerPowerShellDefinition      = "V2CustomizerPowerShell"
	V2CustomizerDefinition                = "V2Customizer"
	V2LayerPropertiesDefinition           = "V2LayerProperties"
	V2BundlePropertiesDefinition          = "V2BundleProperties"
	V2BuildParameterLayerValuesDefinition = "V2BuildParameterLayerValues"
	V2BuildParameterLayersDefinition      = "V2BuildParameterLayers"
	V2BuildParametersDefinition           = "V2BuildParameters"
)
