// Code generated by go generate; DO NOT EDIT.
package avdimagetypes

const (
	V2BundleSchemaName                             = "V2Bundle"
	V2LayerSchemaName                              = "V2Layer"
	V2LayerNetworkConfigSchemaName                 = "V2LayerNetworkConfig"
	V2LayerNetworkWhitelistedInternalIPsSchemaName = "V2LayerNetworkWhitelistedInternalIPs"
	V2LayerNetworkWhitelistedPublicIPSchemaName    = "V2LayerNetworkWhitelistedPublicIP"
	V2LayerAuthorSchemaName                        = "V2LayerAuthor"
	SharedImageVersionSchemaName                   = "SharedImageVersion"
	PlatformImageSchemaName                        = "PlatformImage"
	PlatformImagePlanInfoSchemaName                = "PlatformImagePlanInfo"
	ManagedImageSchemaName                         = "ManagedImage"
)
