// Code generated by github.com/swaggest/json-cli v1.11.2, DO NOT EDIT.

// Package avdimagetypes contains JSON mapping structures.
package avdimagetypes

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// V2BundleProperties structure is generated from "stdin#/definitions/V2BundleProperties".
//
// V2 Bundle Properties.
type V2BundleProperties struct {
	Version         V2BundlePropertiesVersion                 `json:"version"`     // Required.
	CliVersion      string                                    `json:"cli_version"` // Required.
	Layers          []V2LayerProperties                       `json:"layers"`      // Required.
	BuildParameters map[string]map[string]BuildParameterValue `json:"build_parameters,omitempty"`
}

// V2LayerProperties structure is generated from "#/definitions/V2LayerProperties".
//
// V2 Layer Properties.
type V2LayerProperties struct {
	Version V2LayerPropertiesVersion `json:"version"` // Required.
	// Value must match pattern: `^[a-zA-Z0-9-.]+$`.
	// Required.
	Name        string                      `json:"name"`
	Description string                      `json:"description,omitempty"`
	Author      V2LayerPropertiesAuthor     `json:"author"` // Required.
	BaseImage   *V2LayerPropertiesBaseImage `json:"base_image,omitempty"`
	Network     *V2LayerPropertiesNetwork   `json:"network,omitempty"`
	// The version of the AVD platform this layer expects and requires to work.
	// Required.
	PlatformVersion V2LayerPropertiesPlatformVersion `json:"platform_version"`
	// LayerBuildParameters.
	// Parameters required during the build of the image.
	BuildParameters map[string]LayerParameter     `json:"build_parameters,omitempty"`
	Customizers     *V2LayerPropertiesCustomizers `json:"customizers,omitempty"`
}

// V2LayerPropertiesAuthor structure is generated from "#/definitions/V2LayerProperties->author".
type V2LayerPropertiesAuthor struct {
	Name  string `json:"name"`            // Required.
	Email string `json:"email,omitempty"` // Format: email.
}

// ManagedImage structure is generated from "#/definitions/V2LayerProperties->base_image/oneOf/0".
//
// Managed Image.
type ManagedImage struct {
	Type    ManagedImageType `json:"type"`    // Required.
	ImageID string           `json:"imageId"` // Required.
}

// PlatformImage structure is generated from "#/definitions/V2LayerProperties->base_image/oneOf/1".
//
// Platform Image.
type PlatformImage struct {
	Type      PlatformImageType      `json:"type"`               // Required.
	Offer     string                 `json:"offer"`              // Required.
	PlanInfo  *PlatformImagePlanInfo `json:"planInfo,omitempty"` // Platform Image Plan Info.
	Publisher string                 `json:"publisher"`          // Required.
	Sku       string                 `json:"sku"`                // Required.
	Version   string                 `json:"version"`            // Required.
}

// PlatformImagePlanInfo structure is generated from "#/definitions/V2LayerProperties->base_image/oneOf/1->planInfo".
//
// Platform Image Plan Info.
type PlatformImagePlanInfo struct {
	PlanName      string `json:"planName"`      // Required.
	PlanProduct   string `json:"planProduct"`   // Required.
	PlanPublisher string `json:"planPublisher"` // Required.
}

// SharedImageVersion structure is generated from "#/definitions/V2LayerProperties->base_image/oneOf/2".
//
// Shared Image Version.
type SharedImageVersion struct {
	Type           SharedImageVersionType `json:"type"`           // Required.
	ImageVersionID string                 `json:"imageVersionId"` // Required.
}

// V2LayerPropertiesBaseImage structure is generated from "#/definitions/V2LayerProperties->base_image".
type V2LayerPropertiesBaseImage struct {
	ManagedImage       *ManagedImage       `json:"-"`
	PlatformImage      *PlatformImage      `json:"-"`
	SharedImageVersion *SharedImageVersion `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (v *V2LayerPropertiesBaseImage) UnmarshalJSON(data []byte) error {
	var err error

	oneOfErrors := make(map[string]error, 3)
	oneOfValid := 0

	err = json.Unmarshal(data, &v.ManagedImage)
	if err != nil {
		oneOfErrors["ManagedImage"] = err
		v.ManagedImage = nil
	} else {
		oneOfValid++
	}

	err = json.Unmarshal(data, &v.PlatformImage)
	if err != nil {
		oneOfErrors["PlatformImage"] = err
		v.PlatformImage = nil
	} else {
		oneOfValid++
	}

	err = json.Unmarshal(data, &v.SharedImageVersion)
	if err != nil {
		oneOfErrors["SharedImageVersion"] = err
		v.SharedImageVersion = nil
	} else {
		oneOfValid++
	}

	if oneOfValid != 1 {
		return fmt.Errorf("oneOf constraint failed for V2LayerPropertiesBaseImage with %d valid results: %v", oneOfValid, oneOfErrors)
	}

	return nil
}

// MarshalJSON encodes JSON.
func (v V2LayerPropertiesBaseImage) MarshalJSON() ([]byte, error) {
	return marshalUnion(v.ManagedImage, v.PlatformImage, v.SharedImageVersion)
}

// V2LayerPropertiesNetwork structure is generated from "#/definitions/V2LayerProperties->network".
type V2LayerPropertiesNetwork struct {
	HTTPProxyWhitelist []string `json:"http_proxy_whitelist,omitempty"` // HTTP(s) hosts that are whitelisted in the proxy. Note that the application must be configured to use the proxy or support Windows IE proxy settings.
}

// LayerParameter structure is generated from "#/definitions/V2LayerProperties->build_parameters->additionalProperties".
//
// Layer Parameter.
type LayerParameter struct {
	Description string   `json:"description"` // Required.
	Enum        []string `json:"enum,omitempty"`
	Default     string   `json:"default,omitempty"`
}

// V2LayerPropertiesCustomizers structure is generated from "#/definitions/V2LayerProperties->customizers".
type V2LayerPropertiesCustomizers struct {
	Pre  []V2Customizer `json:"pre,omitempty"`
	Post []V2Customizer `json:"post,omitempty"`
}

// V2CustomizerWindowsUpdate structure is generated from "#/definitions/V2CustomizerWindowsUpdate".
type V2CustomizerWindowsUpdate struct {
	Type           V2CustomizerWindowsUpdateType `json:"type"`                     // Required.
	Name           string                        `json:"name"`                     // Required.
	SearchCriteria string                        `json:"searchCriteria,omitempty"` // Windows Update search criteria.
	Filters        []string                      `json:"filters,omitempty"`
	UpdateLimit    uint16                        `json:"updateLimit,omitempty"`
}

// V2CustomizerWindowsRestart structure is generated from "#/definitions/V2CustomizerWindowsRestart".
type V2CustomizerWindowsRestart struct {
	Type                V2CustomizerWindowsRestartType `json:"type"` // Required.
	Name                string                         `json:"name"` // Required.
	RestartCheckCommand string                         `json:"restartCheckCommand,omitempty"`
	RestartCommand      string                         `json:"restartCommand,omitempty"`
	// Timeout in format like '5m', '30s', '1h'.
	// Value must match pattern: `^[0-9]+[smh]$`.
	RestartTimeout string `json:"restartTimeout,omitempty"`
}

// V2CustomizerFile structure is generated from "#/definitions/V2CustomizerFile".
type V2CustomizerFile struct {
	Type V2CustomizerFileType `json:"type"` // Required.
	Name string               `json:"name"` // Required.
	// URL to download the file from.
	// Format: uri.
	// Required.
	SourceURI string `json:"sourceUri"`
	// Local path where file should be saved.
	// Required.
	Destination string `json:"destination"`
	// Expected SHA256 checksum for file validation.
	// Value must match pattern: `^[a-fA-F0-9]{64}$`.
	Sha256Checksum string `json:"sha256Checksum,omitempty"`
}

// V2CustomizerPowerShell structure is generated from "#/definitions/V2CustomizerPowerShell".
type V2CustomizerPowerShell struct {
	Type            V2CustomizerPowerShellType            `json:"type,omitempty"`
	Name            string                                `json:"name,omitempty"`
	Inline          []string                              `json:"inline,omitempty"`          // Array of PowerShell commands/scripts to execute inline.
	Script          string                                `json:"script,omitempty"`          // Path to PowerShell script file to execute.
	ValidExitCodes  []int64                               `json:"validExitCodes,omitempty"`  // List of valid exit codes.
	Elevated        bool                                  `json:"elevated,omitempty"`        // Whether to run PowerShell with elevated privileges.
	System          bool                                  `json:"system,omitempty"`          // Whether to run PowerShell with elevated privileges as the local system user.
	ExecutionPolicy V2CustomizerPowerShellExecutionPolicy `json:"executionPolicy,omitempty"` // PowerShell execution policy for this script.
	// Expected SHA256 checksum for file validation.
	// Value must match pattern: `^[a-fA-F0-9]{64}$`.
	Sha256Checksum string `json:"sha256Checksum,omitempty"`
}

// V2CustomizerPowerShellNot structure is generated from "#/definitions/V2CustomizerPowerShell->not".
type V2CustomizerPowerShellNot struct {
}

// V2Customizer structure is generated from "#/definitions/V2Customizer".
type V2Customizer struct {
	WindowsUpdate  *V2CustomizerWindowsUpdate  `json:"-"`
	WindowsRestart *V2CustomizerWindowsRestart `json:"-"`
	File           *V2CustomizerFile           `json:"-"`
	PowerShell     *V2CustomizerPowerShell     `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (v *V2Customizer) UnmarshalJSON(data []byte) error {
	var err error

	oneOfErrors := make(map[string]error, 4)
	oneOfValid := 0

	err = json.Unmarshal(data, &v.WindowsUpdate)
	if err != nil {
		oneOfErrors["WindowsUpdate"] = err
		v.WindowsUpdate = nil
	} else {
		oneOfValid++
	}

	err = json.Unmarshal(data, &v.WindowsRestart)
	if err != nil {
		oneOfErrors["WindowsRestart"] = err
		v.WindowsRestart = nil
	} else {
		oneOfValid++
	}

	err = json.Unmarshal(data, &v.File)
	if err != nil {
		oneOfErrors["File"] = err
		v.File = nil
	} else {
		oneOfValid++
	}

	err = json.Unmarshal(data, &v.PowerShell)
	if err != nil {
		oneOfErrors["PowerShell"] = err
		v.PowerShell = nil
	} else {
		oneOfValid++
	}

	if oneOfValid != 1 {
		return fmt.Errorf("oneOf constraint failed for V2Customizer with %d valid results: %v", oneOfValid, oneOfErrors)
	}

	return nil
}

// MarshalJSON encodes JSON.
func (v V2Customizer) MarshalJSON() ([]byte, error) {
	return marshalUnion(v.WindowsUpdate, v.WindowsRestart, v.File, v.PowerShell)
}

// BuildParameterValue structure is generated from "#/definitions/V2BuildParameterLayerValues->additionalProperties".
//
// BuildParameterValue.
type BuildParameterValue struct {
	Value string `json:"value"` // Required.
}

// V2BuildParameters structure is generated from "stdin#/definitions/V2BuildParameters".
//
// V2 Build parameters.
type V2BuildParameters struct {
	Version V2BuildParametersVersion                  `json:"version"` // Required.
	Layers  map[string]map[string]BuildParameterValue `json:"layers"`  // Required.
}

// V2BundlePropertiesVersion is an enum type.
type V2BundlePropertiesVersion string

// V2BundlePropertiesVersion values enumeration.
const (
	V2BundlePropertiesVersionV2 = V2BundlePropertiesVersion("v2")
)

// MarshalJSON encodes JSON.
func (i V2BundlePropertiesVersion) MarshalJSON() ([]byte, error) {
	switch i {
	case V2BundlePropertiesVersionV2:

	default:
		return nil, fmt.Errorf("unexpected V2BundlePropertiesVersion value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2BundlePropertiesVersion) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2BundlePropertiesVersion(ii)

	switch v {
	case V2BundlePropertiesVersionV2:

	default:
		return fmt.Errorf("unexpected V2BundlePropertiesVersion value: %v", v)
	}

	*i = v

	return nil
}

// V2LayerPropertiesVersion is an enum type.
type V2LayerPropertiesVersion string

// V2LayerPropertiesVersion values enumeration.
const (
	V2LayerPropertiesVersionV2 = V2LayerPropertiesVersion("v2")
)

// MarshalJSON encodes JSON.
func (i V2LayerPropertiesVersion) MarshalJSON() ([]byte, error) {
	switch i {
	case V2LayerPropertiesVersionV2:

	default:
		return nil, fmt.Errorf("unexpected V2LayerPropertiesVersion value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2LayerPropertiesVersion) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2LayerPropertiesVersion(ii)

	switch v {
	case V2LayerPropertiesVersionV2:

	default:
		return fmt.Errorf("unexpected V2LayerPropertiesVersion value: %v", v)
	}

	*i = v

	return nil
}

// ManagedImageType is a constant type.
type ManagedImageType string

// ManagedImageType values enumeration.
const (
	ManagedImageTypeManagedImage = ManagedImageType("ManagedImage")
)

// MarshalJSON encodes JSON.
func (i ManagedImageType) MarshalJSON() ([]byte, error) {
	switch i {
	case ManagedImageTypeManagedImage:

	default:
		return nil, fmt.Errorf("unexpected ManagedImageType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *ManagedImageType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := ManagedImageType(ii)

	switch v {
	case ManagedImageTypeManagedImage:

	default:
		return fmt.Errorf("unexpected ManagedImageType value: %v", v)
	}

	*i = v

	return nil
}

// PlatformImageType is a constant type.
type PlatformImageType string

// PlatformImageType values enumeration.
const (
	PlatformImageTypePlatformImage = PlatformImageType("PlatformImage")
)

// MarshalJSON encodes JSON.
func (i PlatformImageType) MarshalJSON() ([]byte, error) {
	switch i {
	case PlatformImageTypePlatformImage:

	default:
		return nil, fmt.Errorf("unexpected PlatformImageType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *PlatformImageType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := PlatformImageType(ii)

	switch v {
	case PlatformImageTypePlatformImage:

	default:
		return fmt.Errorf("unexpected PlatformImageType value: %v", v)
	}

	*i = v

	return nil
}

// SharedImageVersionType is a constant type.
type SharedImageVersionType string

// SharedImageVersionType values enumeration.
const (
	SharedImageVersionTypeSharedImageVersion = SharedImageVersionType("SharedImageVersion")
)

// MarshalJSON encodes JSON.
func (i SharedImageVersionType) MarshalJSON() ([]byte, error) {
	switch i {
	case SharedImageVersionTypeSharedImageVersion:

	default:
		return nil, fmt.Errorf("unexpected SharedImageVersionType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *SharedImageVersionType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := SharedImageVersionType(ii)

	switch v {
	case SharedImageVersionTypeSharedImageVersion:

	default:
		return fmt.Errorf("unexpected SharedImageVersionType value: %v", v)
	}

	*i = v

	return nil
}

// V2LayerPropertiesPlatformVersion is an enum type.
type V2LayerPropertiesPlatformVersion string

// V2LayerPropertiesPlatformVersion values enumeration.
const (
	V2LayerPropertiesPlatformVersion2 = V2LayerPropertiesPlatformVersion("2")
)

// MarshalJSON encodes JSON.
func (i V2LayerPropertiesPlatformVersion) MarshalJSON() ([]byte, error) {
	switch i {
	case V2LayerPropertiesPlatformVersion2:

	default:
		return nil, fmt.Errorf("unexpected V2LayerPropertiesPlatformVersion value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2LayerPropertiesPlatformVersion) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2LayerPropertiesPlatformVersion(ii)

	switch v {
	case V2LayerPropertiesPlatformVersion2:

	default:
		return fmt.Errorf("unexpected V2LayerPropertiesPlatformVersion value: %v", v)
	}

	*i = v

	return nil
}

// V2CustomizerWindowsUpdateType is a constant type.
type V2CustomizerWindowsUpdateType string

// V2CustomizerWindowsUpdateType values enumeration.
const (
	V2CustomizerWindowsUpdateTypeWindowsUpdate = V2CustomizerWindowsUpdateType("WindowsUpdate")
)

// MarshalJSON encodes JSON.
func (i V2CustomizerWindowsUpdateType) MarshalJSON() ([]byte, error) {
	switch i {
	case V2CustomizerWindowsUpdateTypeWindowsUpdate:

	default:
		return nil, fmt.Errorf("unexpected V2CustomizerWindowsUpdateType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2CustomizerWindowsUpdateType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2CustomizerWindowsUpdateType(ii)

	switch v {
	case V2CustomizerWindowsUpdateTypeWindowsUpdate:

	default:
		return fmt.Errorf("unexpected V2CustomizerWindowsUpdateType value: %v", v)
	}

	*i = v

	return nil
}

// V2CustomizerWindowsRestartType is a constant type.
type V2CustomizerWindowsRestartType string

// V2CustomizerWindowsRestartType values enumeration.
const (
	V2CustomizerWindowsRestartTypeWindowsRestart = V2CustomizerWindowsRestartType("WindowsRestart")
)

// MarshalJSON encodes JSON.
func (i V2CustomizerWindowsRestartType) MarshalJSON() ([]byte, error) {
	switch i {
	case V2CustomizerWindowsRestartTypeWindowsRestart:

	default:
		return nil, fmt.Errorf("unexpected V2CustomizerWindowsRestartType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2CustomizerWindowsRestartType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2CustomizerWindowsRestartType(ii)

	switch v {
	case V2CustomizerWindowsRestartTypeWindowsRestart:

	default:
		return fmt.Errorf("unexpected V2CustomizerWindowsRestartType value: %v", v)
	}

	*i = v

	return nil
}

// V2CustomizerFileType is a constant type.
type V2CustomizerFileType string

// V2CustomizerFileType values enumeration.
const (
	V2CustomizerFileTypeFile = V2CustomizerFileType("File")
)

// MarshalJSON encodes JSON.
func (i V2CustomizerFileType) MarshalJSON() ([]byte, error) {
	switch i {
	case V2CustomizerFileTypeFile:

	default:
		return nil, fmt.Errorf("unexpected V2CustomizerFileType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2CustomizerFileType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2CustomizerFileType(ii)

	switch v {
	case V2CustomizerFileTypeFile:

	default:
		return fmt.Errorf("unexpected V2CustomizerFileType value: %v", v)
	}

	*i = v

	return nil
}

// V2CustomizerPowerShellType is a constant type.
type V2CustomizerPowerShellType string

// V2CustomizerPowerShellType values enumeration.
const (
	V2CustomizerPowerShellTypePowerShell = V2CustomizerPowerShellType("PowerShell")
)

// MarshalJSON encodes JSON.
func (i V2CustomizerPowerShellType) MarshalJSON() ([]byte, error) {
	switch i {
	case V2CustomizerPowerShellTypePowerShell:

	default:
		return nil, fmt.Errorf("unexpected V2CustomizerPowerShellType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2CustomizerPowerShellType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2CustomizerPowerShellType(ii)

	switch v {
	case V2CustomizerPowerShellTypePowerShell:

	default:
		return fmt.Errorf("unexpected V2CustomizerPowerShellType value: %v", v)
	}

	*i = v

	return nil
}

// V2CustomizerPowerShellExecutionPolicy is an enum type.
type V2CustomizerPowerShellExecutionPolicy string

// V2CustomizerPowerShellExecutionPolicy values enumeration.
const (
	V2CustomizerPowerShellExecutionPolicyBypass       = V2CustomizerPowerShellExecutionPolicy("Bypass")
	V2CustomizerPowerShellExecutionPolicyUnrestricted = V2CustomizerPowerShellExecutionPolicy("Unrestricted")
	V2CustomizerPowerShellExecutionPolicyRemoteSigned = V2CustomizerPowerShellExecutionPolicy("RemoteSigned")
	V2CustomizerPowerShellExecutionPolicyAllSigned    = V2CustomizerPowerShellExecutionPolicy("AllSigned")
	V2CustomizerPowerShellExecutionPolicyRestricted   = V2CustomizerPowerShellExecutionPolicy("Restricted")
)

// MarshalJSON encodes JSON.
func (i V2CustomizerPowerShellExecutionPolicy) MarshalJSON() ([]byte, error) {
	switch i {
	case V2CustomizerPowerShellExecutionPolicyBypass:
	case V2CustomizerPowerShellExecutionPolicyUnrestricted:
	case V2CustomizerPowerShellExecutionPolicyRemoteSigned:
	case V2CustomizerPowerShellExecutionPolicyAllSigned:
	case V2CustomizerPowerShellExecutionPolicyRestricted:

	default:
		return nil, fmt.Errorf("unexpected V2CustomizerPowerShellExecutionPolicy value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2CustomizerPowerShellExecutionPolicy) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2CustomizerPowerShellExecutionPolicy(ii)

	switch v {
	case V2CustomizerPowerShellExecutionPolicyBypass:
	case V2CustomizerPowerShellExecutionPolicyUnrestricted:
	case V2CustomizerPowerShellExecutionPolicyRemoteSigned:
	case V2CustomizerPowerShellExecutionPolicyAllSigned:
	case V2CustomizerPowerShellExecutionPolicyRestricted:

	default:
		return fmt.Errorf("unexpected V2CustomizerPowerShellExecutionPolicy value: %v", v)
	}

	*i = v

	return nil
}

// V2BuildParametersVersion is an enum type.
type V2BuildParametersVersion string

// V2BuildParametersVersion values enumeration.
const (
	V2BuildParametersVersionV2 = V2BuildParametersVersion("v2")
)

// MarshalJSON encodes JSON.
func (i V2BuildParametersVersion) MarshalJSON() ([]byte, error) {
	switch i {
	case V2BuildParametersVersionV2:

	default:
		return nil, fmt.Errorf("unexpected V2BuildParametersVersion value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *V2BuildParametersVersion) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := V2BuildParametersVersion(ii)

	switch v {
	case V2BuildParametersVersionV2:

	default:
		return fmt.Errorf("unexpected V2BuildParametersVersion value: %v", v)
	}

	*i = v

	return nil
}

func marshalUnion(maps ...interface{}) ([]byte, error) {
	result := []byte("{")
	isObject := true

	for _, m := range maps {
		j, err := json.Marshal(m)
		if err != nil {
			return nil, err
		}

		if string(j) == "{}" {
			continue
		}

		if string(j) == "null" {
			continue
		}

		if j[0] != '{' {
			if len(result) == 1 && (isObject || bytes.Equal(result, j)) {
				result = j
				isObject = false

				continue
			}

			return nil, errors.New("failed to union map: object expected, " + string(j) + " received")
		}

		if !isObject {
			return nil, errors.New("failed to union " + string(result) + " and " + string(j))
		}

		if len(result) > 1 {
			result[len(result)-1] = ','
		}

		result = append(result, j[1:]...)
	}

	// Close empty result.
	if isObject && len(result) == 1 {
		result = append(result, '}')
	}

	return result, nil
}
